### ISSUE TITLE
how to run this program correctly?

### ISSUE THREAD

**Issue by Ilia1** [Ruin0x11/pixma_mod#1]
at startup
`lua init.lua`
gives a module search error
> lua: init.lua:1: module 'mod.pixma.data' not found:
	no field package.preload['mod.pixma.data']
	no file '/usr/local/share/lua/5.3/mod/pixma/data.lua'
	no file '/usr/local/share/lua/5.3/mod/pixma/data/init.lua'
	no file '/usr/local/lib/lua/5.3/mod/pixma/data.lua'
	no file '/usr/local/lib/lua/5.3/mod/pixma/data/init.lua'
	no file '/usr/share/lua/5.3/mod/pixma/data.lua'
	no file '/usr/share/lua/5.3/mod/pixma/data/init.lua'
	no file './mod/pixma/data.lua'
	no file './mod/pixma/data/init.lua'
	no file '/usr/local/lib/lua/5.3/mod/pixma/data.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/mod/pixma/data.so'
	no file '/usr/lib/lua/5.3/mod/pixma/data.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './mod/pixma/data.so'
	no file '/usr/local/lib/lua/5.3/mod.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/mod.so'
	no file '/usr/lib/lua/5.3/mod.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
no file './mod.so'
stack traceback:
	[C]: in function 'require'
	init.lua:1: in main chunk
> [C]: in ?

version lua 5.3
P.S. using this program is it possible to scan from a printer to a linux pc?

**Comment by Ruin0x11** [comment]
This repository is actually a mod for a game engine I'm writing, called OpenNefia. However I did write a standalone Lua version of the library that's available here: https://github.com/Ruin0x11/pixma. The only dependencies for that version should be luasocket and lubyk/xml.

Do be aware that it only supports a very specific range of Canon printers, though. And for now it only supports printing, not scanning.

**Comment by Ilia1** [comment]
Thanks for the clarification
